'use strict';

const ExcelJS = require('exceljs');

/**
 * Builds Excel export files. Lives under server/store/ so exceljs stays confined
 * to this folder (CLAUDE.md §1) even though it writes new files rather than
 * touching the data workbooks.
 *
 * Every export is stamped with who generated it and when (SPEC §12 Reports).
 */

const HEADER_FILL = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F2937' } };
const TITLE_FONT = { bold: true, size: 14, color: { argb: 'FF111827' } };
const HEADER_FONT = { bold: true, color: { argb: 'FFFFFFFF' } };

function formatCell(value, type) {
  if (value === null || value === undefined) return '';
  if (type === 'num' || type === 'money') {
    const n = Number(value);
    return Number.isFinite(n) ? n : '';
  }
  if (type === 'bool') return value ? 'Yes' : 'No';
  return value;
}

/**
 * @param {object} spec
 * @param {string} spec.title
 * @param {string} [spec.subtitle]
 * @param {Array<{key:string,label:string,width?:number,type?:string}>} spec.columns
 * @param {Array<object>} spec.rows
 * @param {object} spec.meta { generatedBy, generatedAt, schoolName, filters }
 */
function addSheet(wb, spec) {
  const ws = wb.addWorksheet(sanitiseSheetName(spec.sheetName || spec.title));
  const columnCount = Math.max(1, spec.columns.length);

  let cursor = 1;

  if (spec.meta?.schoolName) {
    ws.mergeCells(cursor, 1, cursor, columnCount);
    const cell = ws.getCell(cursor, 1);
    cell.value = spec.meta.schoolName;
    cell.font = { bold: true, size: 12 };
    cursor += 1;
  }

  ws.mergeCells(cursor, 1, cursor, columnCount);
  const titleCell = ws.getCell(cursor, 1);
  titleCell.value = spec.title;
  titleCell.font = TITLE_FONT;
  cursor += 1;

  if (spec.subtitle) {
    ws.mergeCells(cursor, 1, cursor, columnCount);
    const cell = ws.getCell(cursor, 1);
    cell.value = spec.subtitle;
    cell.font = { italic: true, color: { argb: 'FF6B7280' } };
    cursor += 1;
  }

  const stamp = [
    spec.meta?.generatedBy ? `Generated by ${spec.meta.generatedBy}` : null,
    spec.meta?.generatedAt ? `on ${spec.meta.generatedAt}` : null,
    spec.rows.length === 1 ? '1 row' : `${spec.rows.length} rows`,
  ]
    .filter(Boolean)
    .join(' • ');
  ws.mergeCells(cursor, 1, cursor, columnCount);
  const stampCell = ws.getCell(cursor, 1);
  stampCell.value = stamp;
  stampCell.font = { size: 9, color: { argb: 'FF6B7280' } };
  cursor += 2;

  const headerRowIndex = cursor;
  spec.columns.forEach((column, index) => {
    const cell = ws.getCell(headerRowIndex, index + 1);
    cell.value = column.label;
    cell.font = HEADER_FONT;
    cell.fill = HEADER_FILL;
    cell.alignment = { vertical: 'middle', wrapText: true };
    ws.getColumn(index + 1).width = column.width || Math.max(12, column.label.length + 4);
  });
  ws.getRow(headerRowIndex).height = 20;
  cursor += 1;

  for (const row of spec.rows) {
    spec.columns.forEach((column, index) => {
      const cell = ws.getCell(cursor, index + 1);
      cell.value = formatCell(row[column.key], column.type);
      if (column.type === 'money') cell.numFmt = '#,##0.00';
      if (column.type === 'num') cell.numFmt = '#,##0';
    });
    cursor += 1;
  }

  if (spec.totals) {
    spec.columns.forEach((column, index) => {
      const cell = ws.getCell(cursor, index + 1);
      const value = spec.totals[column.key];
      if (index === 0 && value === undefined) cell.value = 'Total';
      else if (value !== undefined) cell.value = formatCell(value, column.type);
      cell.font = { bold: true };
      if (column.type === 'money') cell.numFmt = '#,##0.00';
    });
  }

  ws.views = [{ state: 'frozen', ySplit: headerRowIndex }];
  ws.autoFilter = {
    from: { row: headerRowIndex, column: 1 },
    to: { row: headerRowIndex, column: columnCount },
  };
  return ws;
}

function sanitiseSheetName(name) {
  return String(name || 'Sheet')
    .replace(/[\\/*?:[\]]/g, '')
    .slice(0, 31);
}

async function buildWorkbook(sheets, meta = {}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = meta.schoolName || 'School Admin Portal';
  wb.created = new Date();
  for (const sheet of sheets) {
    addSheet(wb, { ...sheet, meta: { ...meta, ...(sheet.meta || {}) } });
  }
  return wb.xlsx.writeBuffer();
}

async function buildSingleSheet(spec) {
  return buildWorkbook([spec], spec.meta || {});
}

/** Plain CSV for the parent-contact export that feeds an external bulk SMS tool. */
function buildCsv(columns, rows) {
  const escape = (value) => {
    if (value === null || value === undefined) return '';
    const text = String(value);
    return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };
  const lines = [columns.map((c) => escape(c.label)).join(',')];
  for (const row of rows) {
    lines.push(columns.map((c) => escape(row[c.key])).join(','));
  }
  return `﻿${lines.join('\r\n')}\r\n`;
}

function fileName(base, extension = 'xlsx') {
  const stamp = new Date().toISOString().slice(0, 10);
  const safe = String(base)
    .replace(/[^a-zA-Z0-9-_ ]/g, '')
    .trim()
    .replace(/\s+/g, '-');
  return `${safe}-${stamp}.${extension}`;
}

/**
 * Reads an uploaded workbook into plain rows keyed by header name.
 * Used by the Excel import flow (SPEC §15) — validation happens on these rows,
 * never on the file itself.
 */
async function readUpload(filePath, { sheetName = null, headerRow = 1 } = {}) {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(filePath);
  const ws = sheetName ? wb.getWorksheet(sheetName) : wb.worksheets[0];
  if (!ws) throw new Error('That file has no readable sheet.');

  const headers = [];
  ws.getRow(headerRow).eachCell({ includeEmpty: true }, (cell, colNumber) => {
    headers[colNumber] = String(cellText(cell.value) || '').trim();
  });

  const rows = [];
  for (let r = headerRow + 1; r <= ws.rowCount; r += 1) {
    const excelRow = ws.getRow(r);
    const record = {};
    let empty = true;
    for (let c = 1; c < headers.length; c += 1) {
      const header = headers[c];
      if (!header) continue;
      const value = cellText(excelRow.getCell(c).value);
      record[header] = value;
      if (value !== null && value !== '') empty = false;
    }
    if (empty) continue;
    rows.push({ rowNumber: r, values: record });
  }

  return { headers: headers.filter(Boolean), rows, sheetName: ws.name };
}

/**
 * Schools hand over spreadsheets with merged cells, dates stored as text and
 * formulas — this flattens whatever exceljs hands back into a plain string.
 */
function cellText(value) {
  if (value === null || value === undefined) return null;
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  if (typeof value === 'object') {
    if (value.richText) return value.richText.map((r) => r.text).join('');
    if (value.text !== undefined) return String(value.text);
    if (value.result !== undefined) return String(value.result);
    if (value.hyperlink) return String(value.text || value.hyperlink);
    return null;
  }
  return String(value).trim();
}

/** Builds a versioned import template with a header row and one example row. */
async function buildTemplate({ title, version, columns, example = null, notes = [] }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'School Admin Portal';
  const ws = wb.addWorksheet('Data');

  columns.forEach((column, index) => {
    const cell = ws.getCell(1, index + 1);
    cell.value = column.label;
    cell.font = HEADER_FONT;
    cell.fill = column.required
      ? { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF991B1B' } }
      : HEADER_FILL;
    cell.note = column.hint || undefined;
    ws.getColumn(index + 1).width = column.width || Math.max(14, column.label.length + 4);
  });
  ws.views = [{ state: 'frozen', ySplit: 1 }];

  if (example) {
    columns.forEach((column, index) => {
      ws.getCell(2, index + 1).value = example[column.key] ?? '';
    });
    ws.getRow(2).font = { italic: true, color: { argb: 'FF9CA3AF' } };
  }

  const readme = wb.addWorksheet('Instructions');
  readme.getColumn(1).width = 100;
  const lines = [
    title,
    `Template version: ${version}`,
    '',
    'Red column headings are required. Delete the grey example row before uploading.',
    'Dates must be written as YYYY-MM-DD, for example 2015-04-23.',
    'Nothing is saved until you review the validation report and press Import.',
    '',
    ...notes,
  ];
  lines.forEach((line, index) => {
    const cell = readme.getCell(index + 1, 1);
    cell.value = line;
    if (index === 0) cell.font = TITLE_FONT;
    cell.alignment = { wrapText: true };
  });

  return wb.xlsx.writeBuffer();
}

module.exports = {
  buildWorkbook,
  buildSingleSheet,
  buildCsv,
  buildTemplate,
  readUpload,
  fileName,
  cellText,
};
