using ClosedXML.Excel;
using PdfSharp.Drawing;
using PdfSharp.Fonts;
using PdfSharp.Pdf;
using System.Globalization;
using System.Text;

namespace SchoolPortal.Web.Reporting;

public sealed class ReportExportService
{
    private static readonly object FontSettingsLock = new();
    private static bool fontSettingsConfigured;

    public byte[] ToExcel(ReportData report)
    {
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Report");
        sheet.ShowGridLines = false;

        var lastColumn = Math.Max(1, report.Definition.Columns.Count);
        sheet.Range(1, 1, 1, lastColumn).Merge();
        sheet.Cell(1, 1).Value = report.Definition.Name;
        sheet.Cell(1, 1).Style
            .Font.SetBold()
            .Font.SetFontSize(18)
            .Font.SetFontColor(XLColor.White)
            .Fill.SetBackgroundColor(XLColor.FromHtml("#17365D"))
            .Alignment.SetVertical(XLAlignmentVerticalValues.Center);
        sheet.Row(1).Height = 30;

        sheet.Range(2, 1, 2, lastColumn).Merge();
        sheet.Cell(2, 1).Value =
            $"Generated by {report.RequestedBy} at {report.GeneratedAtUtc:dd MMM yyyy HH:mm:ss} UTC";
        sheet.Cell(2, 1).Style.Font.SetItalic().Font.SetFontColor(
            XLColor.FromHtml("#44546A"));

        sheet.Range(3, 1, 3, lastColumn).Merge();
        sheet.Cell(3, 1).Value = string.Join(" | ", report.Filters.Describe());
        sheet.Cell(3, 1).Style.Font.SetFontColor(XLColor.FromHtml("#44546A"));

        if (report.Definition.IsSensitive)
        {
            sheet.Range(4, 1, 4, lastColumn).Merge();
            sheet.Cell(4, 1).Value =
                "CONFIDENTIAL - Authorized school use only. Export activity is audited.";
            sheet.Cell(4, 1).Style
                .Font.SetBold()
                .Font.SetFontColor(XLColor.FromHtml("#9C0006"))
                .Fill.SetBackgroundColor(XLColor.FromHtml("#FFC7CE"));
        }

        const int headerRow = 6;
        for (var columnIndex = 0;
             columnIndex < report.Definition.Columns.Count;
             columnIndex++)
        {
            var column = report.Definition.Columns[columnIndex];
            var cell = sheet.Cell(headerRow, columnIndex + 1);
            cell.Value = column.Label;
            cell.Style
                .Font.SetBold()
                .Font.SetFontColor(XLColor.White)
                .Fill.SetBackgroundColor(XLColor.FromHtml("#2F75B5"))
                .Alignment.SetVertical(XLAlignmentVerticalValues.Center);
        }

        for (var rowIndex = 0; rowIndex < report.Rows.Count; rowIndex++)
        {
            var row = report.Rows[rowIndex];
            for (var columnIndex = 0;
                 columnIndex < report.Definition.Columns.Count;
                 columnIndex++)
            {
                var column = report.Definition.Columns[columnIndex];
                row.TryGetValue(column.Key, out var value);
                var cell = sheet.Cell(headerRow + rowIndex + 1, columnIndex + 1);
                SetValue(cell, value);
                ApplyNumberFormat(cell, column.Kind);
            }
        }

        var finalRow = Math.Max(headerRow, headerRow + report.Rows.Count);
        var dataRange = sheet.Range(headerRow, 1, finalRow, lastColumn);
        dataRange.SetAutoFilter();
        dataRange.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
        dataRange.Style.Border.OutsideBorderColor =
            XLColor.FromHtml("#D9E2F3");
        sheet.SheetView.FreezeRows(headerRow);
        sheet.Columns(1, lastColumn).AdjustToContents(1, finalRow);
        foreach (var column in sheet.Columns(1, lastColumn))
        {
            if (column.Width > 42)
            {
                column.Width = 42;
            }
        }

        sheet.PageSetup.PageOrientation = XLPageOrientation.Landscape;
        sheet.PageSetup.FitToPages(1, 0);
        sheet.PageSetup.SetRowsToRepeatAtTop(1, headerRow);
        sheet.PageSetup.Footer.Center.AddText(
            "School Administration Portal - confidential where marked");
        sheet.PageSetup.Footer.Right.AddText("Page &P of &N");

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public byte[] ToCsv(ReportData report)
    {
        var builder = new StringBuilder();
        builder.AppendLine(string.Join(
            ',',
            report.Definition.Columns.Select(column => Csv(column.Label))));
        foreach (var row in report.Rows)
        {
            builder.AppendLine(string.Join(
                ',',
                report.Definition.Columns.Select(column =>
                {
                    row.TryGetValue(column.Key, out var value);
                    return Csv(Format(value, column.Kind));
                })));
        }

        return new UTF8Encoding(encoderShouldEmitUTF8Identifier: true)
            .GetBytes(builder.ToString());
    }

    public byte[] ToPdf(ReportData report)
    {
        ConfigureFonts();
        using var document = new PdfDocument
        {
            Info =
            {
                Title = report.Definition.Name,
                Author = report.RequestedBy,
                Subject = "School Administration Portal report export",
            },
        };
        var titleFont = new XFont("Arial", 16, XFontStyleEx.Bold);
        var metaFont = new XFont("Arial", 8, XFontStyleEx.Regular);
        var headerFont = new XFont("Arial", 7, XFontStyleEx.Bold);
        var bodyFont = new XFont("Arial", 7, XFontStyleEx.Regular);
        var pageNumber = 0;
        PdfPage? page = null;
        XGraphics? graphics = null;
        var y = 0d;
        var columnWidths = GetColumnWidths(report.Definition.Columns);
        const double margin = 30;
        const double rowHeight = 18;

        void StartPage()
        {
            graphics?.Dispose();
            page = document.AddPage();
            page.Orientation = PdfSharp.PageOrientation.Landscape;
            page.Size = PdfSharp.PageSize.A4;
            graphics = XGraphics.FromPdfPage(page);
            pageNumber++;
            y = margin;
            graphics.DrawString(
                report.Definition.Name,
                titleFont,
                XBrushes.DarkBlue,
                new XRect(margin, y, page.Width.Point - margin * 2, 24),
                XStringFormats.TopLeft);
            y += 24;
            graphics.DrawString(
                $"Generated by {report.RequestedBy} at {report.GeneratedAtUtc:dd MMM yyyy HH:mm:ss} UTC",
                metaFont,
                XBrushes.DimGray,
                new XRect(margin, y, page.Width.Point - margin * 2, 12),
                XStringFormats.TopLeft);
            y += 12;
            graphics.DrawString(
                string.Join(" | ", report.Filters.Describe()),
                metaFont,
                XBrushes.DimGray,
                new XRect(margin, y, page.Width.Point - margin * 2, 12),
                XStringFormats.TopLeft);
            y += 14;
            if (report.Definition.IsSensitive)
            {
                graphics.DrawString(
                    "CONFIDENTIAL - Authorized school use only - Export activity is audited",
                    headerFont,
                    XBrushes.DarkRed,
                    new XRect(margin, y, page.Width.Point - margin * 2, 12),
                    XStringFormats.TopLeft);
                y += 14;
            }

            DrawTableRow(
                graphics,
                y,
                report.Definition.Columns.Select(x => x.Label).ToArray(),
                columnWidths,
                headerFont,
                XBrushes.White,
                new XSolidBrush(XColor.FromArgb(47, 117, 181)),
                rowHeight,
                margin);
            y += rowHeight;
        }

        StartPage();
        foreach (var row in report.Rows)
        {
            if (page is null || graphics is null)
            {
                throw new InvalidOperationException("PDF page was not initialized.");
            }

            if (y + rowHeight + 22 > page.Height.Point - margin)
            {
                DrawFooter(graphics, page, pageNumber, metaFont, margin);
                StartPage();
            }

            var values = report.Definition.Columns
                .Select(column =>
                {
                    row.TryGetValue(column.Key, out var value);
                    return Format(value, column.Kind);
                })
                .ToArray();
            DrawTableRow(
                graphics!,
                y,
                values,
                columnWidths,
                bodyFont,
                XBrushes.Black,
                XBrushes.White,
                rowHeight,
                margin);
            y += rowHeight;
        }

        if (page is not null && graphics is not null)
        {
            DrawFooter(graphics, page, pageNumber, metaFont, margin);
        }

        graphics?.Dispose();
        using var stream = new MemoryStream();
        document.Save(stream, false);
        return stream.ToArray();
    }

    private static void ConfigureFonts()
    {
        lock (FontSettingsLock)
        {
            if (fontSettingsConfigured)
            {
                return;
            }

            if (OperatingSystem.IsWindows())
            {
                GlobalFontSettings.UseWindowsFontsUnderWindows = true;
            }

            fontSettingsConfigured = true;
        }
    }

    private static void SetValue(IXLCell cell, object? value)
    {
        switch (value)
        {
            case null:
                cell.Clear(XLClearOptions.Contents);
                break;
            case DateOnly date:
                cell.Value = date.ToDateTime(TimeOnly.MinValue);
                break;
            case DateTimeOffset dateTime:
                cell.Value = dateTime.UtcDateTime;
                break;
            case int integer:
                cell.Value = integer;
                break;
            case long longValue:
                cell.Value = longValue;
                break;
            case decimal decimalValue:
                cell.Value = decimalValue;
                break;
            case double doubleValue:
                cell.Value = doubleValue;
                break;
            case bool boolean:
                cell.Value = boolean;
                break;
            default:
                cell.Value = Convert.ToString(
                    value,
                    System.Globalization.CultureInfo.InvariantCulture);
                break;
        }
    }

    private static void ApplyNumberFormat(
        IXLCell cell,
        ReportValueKind kind)
    {
        cell.Style.NumberFormat.Format = kind switch
        {
            ReportValueKind.WholeNumber => "#,##0",
            ReportValueKind.Number => "#,##0.00",
            ReportValueKind.Percentage => "0.0%",
            ReportValueKind.Date => "dd mmm yyyy",
            ReportValueKind.DateTime => "dd mmm yyyy hh:mm",
            _ => "@",
        };
        cell.Style.Alignment.Horizontal = kind is ReportValueKind.WholeNumber
            or ReportValueKind.Number
            or ReportValueKind.Percentage
            ? XLAlignmentHorizontalValues.Right
            : XLAlignmentHorizontalValues.Left;
    }

    private static double[] GetColumnWidths(
        IReadOnlyList<ReportColumn> columns)
    {
        var total = columns.Sum(column => column.Kind switch
        {
            ReportValueKind.WholeNumber => 0.7,
            ReportValueKind.Number or ReportValueKind.Percentage => 0.9,
            ReportValueKind.Date or ReportValueKind.DateTime => 1.05,
            _ => 1.35,
        });
        const double available = 780;
        return columns.Select(column =>
        {
            var weight = column.Kind switch
            {
                ReportValueKind.WholeNumber => 0.7,
                ReportValueKind.Number or ReportValueKind.Percentage => 0.9,
                ReportValueKind.Date or ReportValueKind.DateTime => 1.05,
                _ => 1.35,
            };
            return available * weight / total;
        }).ToArray();
    }

    private static void DrawTableRow(
        XGraphics graphics,
        double y,
        string[] values,
        double[] widths,
        XFont font,
        XBrush textBrush,
        XBrush backgroundBrush,
        double rowHeight,
        double margin)
    {
        var x = margin;
        for (var index = 0; index < values.Length; index++)
        {
            var rectangle = new XRect(x, y, widths[index], rowHeight);
            graphics.DrawRectangle(
                new XPen(XColor.FromArgb(217, 226, 243), 0.5),
                backgroundBrush,
                rectangle);
            var text = values[index];
            if (text.Length > 28)
            {
                text = text[..25] + "...";
            }

            graphics.DrawString(
                text,
                font,
                textBrush,
                new XRect(x + 3, y + 3, widths[index] - 6, rowHeight - 6),
                XStringFormats.TopLeft);
            x += widths[index];
        }
    }

    private static void DrawFooter(
        XGraphics graphics,
        PdfPage page,
        int pageNumber,
        XFont font,
        double margin)
    {
        graphics.DrawString(
            $"School Administration Portal | Page {pageNumber}",
            font,
            XBrushes.DimGray,
            new XRect(
                margin,
                page.Height.Point - margin + 4,
                page.Width.Point - margin * 2,
                12),
            XStringFormats.TopRight);
    }

    private static string Csv(string value)
    {
        var safe = value;
        if (safe.Length > 0 && safe[0] is '=' or '+' or '-' or '@')
        {
            safe = "'" + safe;
        }

        var quote = ((char)34).ToString();
        return quote + safe.Replace(quote, quote + quote) + quote;
    }

    private static string Format(object? value, ReportValueKind kind) =>
        value switch
        {
            null => string.Empty,
            DateOnly date => date.ToString("dd MMM yyyy", CultureInfo.InvariantCulture),
            DateTimeOffset date => date.ToString("dd MMM yyyy HH:mm", CultureInfo.InvariantCulture),
            decimal number when kind == ReportValueKind.Percentage =>
                number.ToString("P1", CultureInfo.InvariantCulture),
            decimal number => number.ToString("N2", CultureInfo.InvariantCulture),
            double number when kind == ReportValueKind.Percentage =>
                number.ToString("P1", CultureInfo.InvariantCulture),
            _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty,
        };
}
